# Generated by Django 6.0.8 on 2026-08-24 06:26

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=120)),
                (
                    "recency",
                    models.CharField(
                        choices=[
                            ("recent", "recent"),
                            ("onemonth", "onemonth"),
                            ("year", "year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=200)),
                ("practice", models.CharField(max_length=200)),
                ("cc_number", models.CharField(max_length=40)),
                ("practice_phone", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("enrolled", "enrolled"),
                            ("declined", "declined"),
                            ("callback", "callback"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FaqChunk",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=200)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("embedding", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "faq_chunks",
                "ordering": ["category"],
            },
        ),
    ]
