# Generated by Django 6.0.8 on 2026-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_remove_conversation_messages_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="openai_thread_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
