# Generated by Django 6.0.8 on 2026-08-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_conversation_openai_thread_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="openai_thread_id",
        ),
        migrations.AddField(
            model_name="conversation",
            name="openai_conv_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
