# Generated by Django 6.0.8 on 2026-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_remove_conversation_openai_thread_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.AddField(
            model_name="message",
            name="conversation_id",
            field=models.CharField(db_index=True, default="default", max_length=255),
            preserve_default=False,
        ),
    ]
