# Generated by Django 6.0.8 on 2026-08-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_remove_message_conversation_message_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "created"), (2, "updated"), (3, "deleted")], default=1
            ),
        ),
        migrations.AddField(
            model_name="faqchunk",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "created"), (2, "updated"), (3, "deleted")], default=1
            ),
        ),
        migrations.AddField(
            model_name="faqchunk",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="message",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "created"), (2, "updated"), (3, "deleted")], default=1
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
