# Generated by Django 6.0.8 on 2026-08-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_conversation_action_type_faqchunk_action_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="openai_conv_id",
            new_name="conv_id",
        ),
    ]
