# Generated by Django 6.0.8 on 2026-08-27 11:34

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_conversation_latest_appointment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturedPatient",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capture_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("email", models.CharField(blank=True, max_length=254)),
                ("patient_name", models.CharField(max_length=120)),
                ("provider", models.CharField(blank=True, max_length=200)),
                ("practice", models.CharField(blank=True, max_length=200)),
                ("cc_number", models.CharField(blank=True, max_length=40)),
                ("practice_phone", models.CharField(blank=True, max_length=40)),
                (
                    "latest_appointment_date",
                    models.CharField(blank=True, max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.IntegerField(
                        choices=[(1, "created"), (2, "updated"), (3, "deleted")],
                        default=1,
                    ),
                ),
            ],
            options={
                "db_table": "captured_patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="patient_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
