# Generated by Django 6.0.8 on 2026-08-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0009_capturedpatient_conversation_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturedpatient",
            name="link_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
