# Generated by Django 6.0.8 on 2026-08-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0010_capturedpatient_link_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capturedpatient",
            name="latest_appointment_date",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="latest_appointment_date",
        ),
        migrations.AddField(
            model_name="capturedpatient",
            name="recency",
            field=models.CharField(
                choices=[("onemonth", "onemonth"), ("year", "year")],
                default="year",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="recency",
            field=models.CharField(
                choices=[("onemonth", "onemonth"), ("year", "year")],
                default="year",
                max_length=20,
            ),
        ),
    ]
