# Generated by Django 6.0.8 on 2026-08-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_remove_capturedpatient_latest_appointment_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CapturedPatient",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="conversation",
            name="capture_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="conversation",
            name="email",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="conversation",
            name="link_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="cc_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="conv_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="practice",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="practice_phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="provider",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
