# Generated by Django 6.0.8 on 2026-08-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0012_delete_capturedpatient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="capture_id",
        ),
    ]
