# Generated by Django 6.0.8 on 2026-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0013_remove_conversation_capture_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="cc_number",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="practice_phone",
        ),
        migrations.AddField(
            model_name="conversation",
            name="capture_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
