# Generated by Django 6.0.8 on 2026-08-28 09:25

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0017_remove_conversation_conv_id_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="patient_id",
            field=django_mongodb_backend.fields.ObjectIdField(db_index=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="capture_id",
            field=django_mongodb_backend.fields.ObjectIdField(
                blank=True, db_index=True, null=True
            ),
        ),
    ]
