# Generated by Django 6.0.8 on 2026-08-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0019_string_ids_to_object_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="capture_id",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="email",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="link_sent_at",
        ),
    ]
