# Generated by Django 6.0.8 on 2026-08-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0021_chatbot_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="patient_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="chat",
            name="patient_profile",
            field=models.TextField(blank=True),
        ),
    ]
