# Generated by Django 6.0.8 on 2026-08-31 05:37

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0022_chat_patient_id_chat_patient_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="chat_id",
            field=django_mongodb_backend.fields.ObjectIdField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="patient_id",
            field=django_mongodb_backend.fields.ObjectIdField(
                blank=True, db_index=True, null=True
            ),
        ),
    ]
