# Generated by Django 6.0.8 on 2026-08-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0024_backfill_object_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="care_companion_number",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="practice_phone",
        ),
    ]
