# Generated by Django 6.0.8 on 2026-08-31 08:41

import utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0029_conv_ids_one_record_per_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "Created"), (2, "Updated"), (3, "Deleted")],
                default=utils.enums.ActionType["Created"],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "user"), ("assistant", "assistant")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="remoteenrollement",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "Created"), (2, "Updated"), (3, "Deleted")],
                default=utils.enums.ActionType["Created"],
            ),
        ),
        migrations.AlterField(
            model_name="remoteenrollement",
            name="recency",
            field=models.CharField(
                choices=[("onemonth", "oneMonth"), ("year", "year")],
                default=utils.enums.Recency["year"],
                max_length=20,
            ),
        ),
    ]
