# Generated by Django 6.0.8 on 2026-09-01 05:35

import utils.enums
from django.db import migrations, models


def callback_to_active(apps, schema_editor):
    """`callback` is gone; those chats were never settled, so they go back to
    being open conversations rather than sitting on a status that no longer
    exists."""
    RemoteEnrollement = apps.get_model("database", "RemoteEnrollement")
    RemoteEnrollement.objects.filter(status="callback").update(status="active")


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0030_alter_message_action_type_alter_message_role_and_more"),
    ]

    operations = [
        migrations.RunPython(callback_to_active, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="remoteenrollement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("enrolled", "enrolled"),
                    ("declined", "declined"),
                ],
                default=utils.enums.ChatStatus["active"],
                max_length=20,
            ),
        ),
    ]
