# Generated by Django 6.0.8 on 2026-09-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0034_reviewed_scripts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remoteenrollement",
            name="consent_version",
        ),
    ]
