# Generated by Django 6.0.8 on 2026-09-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0035_remove_remoteenrollement_consent_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remoteenrollement",
            name="consented_at",
        ),
        migrations.AlterField(
            model_name="message",
            name="tenant",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
    ]
