# Generated by Django 6.0.8 on 2026-09-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0036_remove_remoteenrollement_consented_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="remoteenrollement_id",
        ),
        migrations.RemoveField(
            model_name="message",
            name="tenant",
        ),
    ]
