# Generated by Django 6.0.8 on 2026-09-05 12:51

import django_mongodb_backend.fields
import utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0037_remove_message_remoteenrollement_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("version", models.IntegerField(default=1)),
                ("updated_by", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.IntegerField(
                        choices=[(1, "Created"), (2, "Updated"), (3, "Deleted")],
                        default=utils.enums.ActionType["Created"],
                    ),
                ),
            ],
            options={
                "db_table": "system_prompts",
                "ordering": ["-version"],
            },
        ),
    ]
