# Generated by Django 6.0.8 on 2026-09-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0040_delete_faqchunk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RemoteEnrollement",
        ),
    ]
