# Generated by Django 6.0.8 on 2026-09-07 06:53

import django_mongodb_backend.fields
import utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0041_delete_remoteenrollement"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptFile",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("s3_key", models.CharField(max_length=500)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.IntegerField(default=0)),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.IntegerField(
                        choices=[(1, "Created"), (2, "Updated"), (3, "Deleted")],
                        default=utils.enums.ActionType["Created"],
                    ),
                ),
            ],
            options={
                "db_table": "prompt_files",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("updated_by", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.IntegerField(
                        choices=[(1, "Created"), (2, "Updated"), (3, "Deleted")],
                        default=utils.enums.ActionType["Created"],
                    ),
                ),
            ],
            options={
                "db_table": "system_prompts",
            },
        ),
    ]
