# Generated by Django 6.0.8 on 2026-09-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0042_promptfile_systemprompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemprompt",
            name="chatbot_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
