# Generated by Django 6.0.8 on 2026-09-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0043_systemprompt_chatbot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemprompt",
            name="tennet_id",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
