# Generated by Django 6.0.8 on 2026-09-07 12:11

import django_mongodb_backend.fields
import utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0046_rename_tennet_id_to_tenant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    django_mongodb_backend.fields.ObjectIdField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "file_id",
                    django_mongodb_backend.fields.ObjectIdField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("ordinal", models.IntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "embedding",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, default=list
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.IntegerField(
                        choices=[(1, "Created"), (2, "Updated"), (3, "Deleted")],
                        default=utils.enums.ActionType["Created"],
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["ordinal"],
            },
        ),
        migrations.AddField(
            model_name="promptfile",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
