# Generated by Django 6.0.8 on 2026-09-09 19:24

import utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0047_documentchunk_promptfile_content_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "Created"), (2, "Updated"), (3, "Deleted"), (4, "Queued")],
                default=utils.enums.ActionType["Created"],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "Created"), (2, "Updated"), (3, "Deleted"), (4, "Queued")],
                default=utils.enums.ActionType["Created"],
            ),
        ),
        migrations.AlterField(
            model_name="promptfile",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "Created"), (2, "Updated"), (3, "Deleted"), (4, "Queued")],
                default=utils.enums.ActionType["Created"],
            ),
        ),
        migrations.AlterField(
            model_name="systemprompt",
            name="action_type",
            field=models.IntegerField(
                choices=[(1, "Created"), (2, "Updated"), (3, "Deleted"), (4, "Queued")],
                default=utils.enums.ActionType["Created"],
            ),
        ),
    ]
